"""Compile, gate, exact-check, and atomically publish generated color tables.

usage: python -m dartwork_mpl._colors._build
결정론: 같은 소스에서 byte-identical 출력 (timestamp·랜덤 없음, key 정렬).
"""

import argparse
import os
import stat
import sys
import tempfile
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import cast

from ._catalog import (
    CatalogSnapshot,
    compile_candidate_snapshot,
    load_v5_snapshot,
)
from ._comparison import compare_exact_surfaces
from ._gates import evaluate_catalog, load_quality_baseline
from ._ssot import load_color_v6_ssot

__all__ = ["main"]

_OUT = Path(__file__).parent / "_generated.py"
_HEADER = '''"""AUTO-GENERATED by dartwork_mpl._colors._build — do not edit.

Regenerate: python -m dartwork_mpl._colors._build
Source of truth: asset/color/color_v6_ssot.json (NeutralTone authority).
"""

'''


def _fmt(name: str, table: Mapping[str, Sequence[str]]) -> str:
    lines = [f"{name}: dict[str, tuple[str, ...]] = {{"]
    for key in sorted(table):
        row = ", ".join(f'"{h}"' for h in table[key])
        lines.append(f'    "{key}": ({row}),')
    lines.append("}\n")
    return "\n".join(lines)


def _fmt_multi_hue_indices(
    manifest: Mapping[str, Mapping[str, Sequence[int]]],
) -> str:
    """Format the validated index manifest as a deterministic literal."""
    lines = [
        "MULTI_HUE_DISCRETE_INDICES: dict[str, dict[int, tuple[int, ...]]] = {"
    ]
    for family in sorted(manifest):
        lines.append(f'    "{family}": {{')
        for size_text in sorted(manifest[family], key=int):
            row = manifest[family][size_text]
            values = ", ".join(str(index) for index in row)
            if len(row) == 1:
                values += ","
            lines.append(f"        {int(size_text)}: ({values}),")
        lines.append("    },")
    lines.append("}\n")
    return "\n".join(lines)


def _render_generated(candidate: CatalogSnapshot) -> str:
    """Render the complete expected generated module without side effects."""
    authority = load_color_v6_ssot()
    multi_hue_indices = cast(
        Mapping[str, Mapping[str, Sequence[int]]],
        authority["multi_hue_discrete_indices"],
    )
    body = (
        _fmt("PALETTE", candidate.palette)
        + "\n"
        + _fmt("CYCLES", candidate.cycles)
        + "\n"
        + _fmt("CMAPS_256", candidate.cmaps_256)
        + "\n"
        + _fmt_multi_hue_indices(multi_hue_indices)
    )
    return _HEADER + body


def _set_temporary_mode(descriptor: int, temporary: Path, mode: int) -> None:
    """Set temporary permissions through the best platform capability."""
    fchmod = getattr(os, "fchmod", None)
    if callable(fchmod):
        fchmod(descriptor, mode)
        return
    os.chmod(temporary, mode)


def _atomic_write_text(target: Path, text: str) -> None:
    """Fsync a unique sibling temporary and atomically replace ``target``."""
    target_mode = (
        stat.S_IMODE(target.stat().st_mode) if target.exists() else 0o644
    )
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{target.name}.", suffix=".tmp", dir=target.parent
    )
    temporary = Path(temporary_name)
    descriptor_owned = True
    try:
        _set_temporary_mode(descriptor, temporary, target_mode)
        stream = os.fdopen(descriptor, "w", encoding="utf-8", newline="")
        descriptor_owned = False
        with stream:
            stream.write(text)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, target)
    finally:
        if descriptor_owned:
            os.close(descriptor)
        temporary.unlink(missing_ok=True)


def _has_exact_mismatches(comparisons: Mapping[str, object]) -> bool:
    """Return whether any exact-surface comparison retains mismatched leaves."""
    return any(
        bool(getattr(comparison, "mismatch_count", 0))
        for comparison in comparisons.values()
    )


def _print_gate_failures(violations: Sequence[object]) -> None:
    """Render shared gate failures without imposing a second policy."""
    for violation in violations:
        asset = getattr(violation, "asset", "catalog")
        metric = getattr(violation, "metric", "unknown")
        observed = getattr(violation, "observed", "unknown")
        allowed = getattr(violation, "allowed", "unknown")
        rule = getattr(violation, "rule", "unknown")
        print(
            f"GATE FAIL: {asset} {metric}: {observed} {rule} {allowed}",
            file=sys.stderr,
        )


def main(argv: Sequence[str] | None = None) -> int:
    """Run compile → gate → exact → render → check/publish once."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=_OUT)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    target = arguments.output

    candidate = compile_candidate_snapshot()
    quality_baseline = load_quality_baseline()
    gate_report = evaluate_catalog(candidate, quality_baseline)
    if not gate_report.passed:
        _print_gate_failures(gate_report.violations)
        return 1

    baseline = load_v5_snapshot()
    exact = compare_exact_surfaces(baseline, candidate)
    if _has_exact_mismatches(exact):
        print("EXACT FAIL: candidate differs from frozen v5", file=sys.stderr)
        return 1

    expected = _render_generated(candidate)
    expected_bytes = expected.encode("utf-8")
    fresh = target.is_file() and target.read_bytes() == expected_bytes
    if arguments.check:
        return 0 if fresh else 2
    if fresh:
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    _atomic_write_text(target, expected)
    print(f"OK: {target} (exact and full-catalog gates green)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
