"""Build CLI — 107-number SSOT에서 전 산출물 컴파일 + A7 게이트 + _generated.py.

usage: python -m dartwork_mpl.colors._build
결정론: 같은 소스에서 byte-identical 출력 (timestamp·랜덤 없음, key 정렬).
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

from ._cmaps import compile_cmaps
from ._cycles import CYCLE_SPECS, cycle_hexes
from ._gates import check_all
from ._generate import compile_palette

__all__ = ["main"]

_OUT = Path(__file__).parent / "_generated.py"
_HEADER = '''"""AUTO-GENERATED by dartwork_mpl.colors._build — do not edit.

Regenerate: python -m dartwork_mpl.colors._build
Source of truth: colors/_recipe.py (107-number SSOT, spec 2026-07-03).
"""

from __future__ import annotations

'''

# Cmap category prefixes (gate runner's `kind` dispatch — see ._gates.check_all).
_DIVERGING_CMAPS = {
    "blue_red",
    "blue_red_deep",
    "blue_red_soft",
    "blue_orange",
    "teal_rose",
    "green_purple",
    "purple_orange",
    "cyan_red",
    "teal_amber",
    "violet_lime",
    "indigo_amber",
    "gray_blue",
    "gray_red",
}
_CYCLIC_CMAPS = {"hue", "halo", "corona"}


def _fmt(name: str, table: dict[str, list[str]]) -> str:
    lines = [f"{name}: dict[str, tuple[str, ...]] = {{"]
    for key in sorted(table):
        row = ", ".join(f'"{h}"' for h in table[key])
        lines.append(f'    "{key}": ({row}),')
    lines.append("}\n")
    return "\n".join(lines)


def _prefixed(cmaps: dict[str, list[str]]) -> dict[str, list[str]]:
    """Tag each cmap key with its gate category (``div.``/``topo.``/``cyc.``/``seq.``)."""
    out: dict[str, list[str]] = {}
    for key, hexes in cmaps.items():
        if key in _DIVERGING_CMAPS:
            out[f"div.{key}"] = hexes
        elif key in _CYCLIC_CMAPS:
            out[f"cyc.{key}"] = hexes
        elif key == "coast":
            out[f"topo.{key}"] = hexes
        else:
            out[f"seq.{key}"] = hexes
    return out


def main() -> int:
    palette = compile_palette()
    cycles = {name: cycle_hexes(name, palette) for name in CYCLE_SPECS}
    cmaps32 = compile_cmaps(palette, n=32)  # gate on 32-stop direct render
    cmaps256 = compile_cmaps(palette, n=256)  # export table

    violations = check_all(palette, cycles, _prefixed(cmaps32))
    if violations:
        for violation in violations:
            print(f"GATE FAIL: {violation}", file=sys.stderr)
        return 1

    body = (
        _fmt("PALETTE", palette)
        + "\n"
        + _fmt("CYCLES", cycles)
        + "\n"
        + _fmt("CMAPS_256", cmaps256)
    )
    # Atomic write: stage in a temp file in the same directory, then
    # os.replace (atomic on POSIX) into the tracked _generated.py — a
    # crash mid-write can never leave the committed source truncated
    # or half-written.
    tmp_path = _OUT.with_suffix(_OUT.suffix + ".tmp")
    tmp_path.write_text(_HEADER + body, encoding="utf-8")
    os.replace(tmp_path, _OUT)
    print(
        f"OK: {_OUT} ({len(palette)} families, {len(cmaps256)} cmaps, "
        "gates green)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
