"""Curated dartwork categorical palettes (dc.*) — hand-tuned SSOT.

These are the scientifically curated qualitative / duo / diverging / tone
categorical palette SETS carried over from the 0.5.5 categorical overhaul and
integrated with the v5 color system. Each palette is registered as
``dc.<name><step>`` numbered tokens (colors/_loader.py) so ``get_palette`` /
``set_cycle`` resolve them exactly like the generated v5 families.

The single-hue SEQUENTIAL ramps teal / indigo / gray are intentionally NOT
here — the recipe-generated v5 families ``dc.teal`` / ``dc.indigo`` / ``dc.gray``
(10 perceptually-equalized steps) supersede them. The preserved curated sets
have no generative v5 equivalent; sequential curated ramps follow dartwork's
light-to-dark index convention.
"""

from __future__ import annotations

# Display / rail order, grouped by intent family (see CURATED_META).
CURATED_ORDER: tuple[str, ...] = (
    "warm_gray",
    "cool_gray",
    "forest",
    "teal_indigo",
    "blue_orange",
    "teal_coral",
    "trustworthy",
    "pastel",
    "dusty",
    "vivid",
    "neon",
    "ember",
    "earth",
    "jewel",
    "cool_warm",
    "teal_amber",
    "purple_green",
    "teal_accent",
    "coral_accent",
    "accessible",
)

# name -> verbatim curated hex ramp (8 steps each).
CURATED: dict[str, tuple[str, ...]] = {
    "warm_gray": (
        "#efe7df",
        "#d3cbc3",
        "#b7afa8",
        "#9d958e",
        "#827b74",
        "#69625b",
        "#514a44",
        "#3a342e",
    ),
    "cool_gray": (
        "#deeaf3",
        "#c2ced6",
        "#a7b2bb",
        "#8d97a0",
        "#737d85",
        "#5b656c",
        "#434d54",
        "#2d363d",
    ),
    "forest": (
        "#475b26",
        "#8cac74",
        "#5b8554",
        "#a4daa8",
        "#37734d",
        "#80c6a0",
        "#619b70",
        "#c7eeb4",
    ),
    "teal_indigo": (
        "#056463",
        "#4cb3c3",
        "#2b88aa",
        "#a1d3ff",
        "#486d9d",
        "#aeb6ed",
        "#958bbf",
        "#f3daff",
    ),
    "blue_orange": (
        "#036085",
        "#2485c2",
        "#17b2e3",
        "#b1cfff",
        "#a9532c",
        "#cb8043",
        "#fea18a",
        "#ffddba",
    ),
    "teal_coral": (
        "#01655c",
        "#0d8d8a",
        "#2ab9a1",
        "#3ae3e7",
        "#ae5029",
        "#d07d3e",
        "#ffa183",
        "#ffdcbe",
    ),
    "trustworthy": (
        "#06655a",
        "#72a6db",
        "#8076a9",
        "#ffb8a5",
        "#467647",
        "#ef9dc2",
        "#83919c",
        "#d0dfeb",
    ),
    "pastel": (
        "#538789",
        "#aeb9da",
        "#bc918b",
        "#c0e0c7",
        "#a68398",
        "#d3c8a7",
        "#8bafc8",
        "#dbeaf6",
    ),
    "dusty": (
        "#346162",
        "#8992ae",
        "#916d68",
        "#9cb8a2",
        "#7c5f71",
        "#aba285",
        "#69889e",
        "#b4c3cf",
    ),
    "vivid": (
        "#04696f",
        "#05a7f7",
        "#cb5a51",
        "#81d383",
        "#9455a6",
        "#cbac4d",
        "#8f82dd",
        "#51eabb",
    ),
    "neon": (
        "#045f5e",
        "#02a5f5",
        "#a357c4",
        "#ffa9db",
        "#5f6c02",
        "#e4a431",
        "#5584f8",
        "#08f2cc",
    ),
    "ember": (
        "#942732",
        "#e6835f",
        "#9e6b29",
        "#d9c778",
        "#536a26",
        "#ff91ab",
        "#c17746",
        "#d0dfeb",
    ),
    "earth": (
        "#80443a",
        "#cb9375",
        "#94744b",
        "#d6c898",
        "#666a3d",
        "#e5a48e",
        "#a0895f",
        "#d1e3b7",
    ),
    "jewel": (
        "#02504f",
        "#25a88a",
        "#0375a0",
        "#b3bdfe",
        "#963c3e",
        "#caa65e",
        "#a26eb0",
        "#42ecfb",
    ),
    "cool_warm": (
        "#055f8b",
        "#3b8bba",
        "#81b7db",
        "#bcdcf1",
        "#f5cec9",
        "#dfa19c",
        "#bb6f6e",
        "#943d45",
    ),
    "teal_amber": (
        "#06655c",
        "#209389",
        "#74bdb6",
        "#b4e0db",
        "#ebd3bc",
        "#d0a987",
        "#aa7951",
        "#844c21",
    ),
    "purple_green": (
        "#523f87",
        "#8573aa",
        "#b9abcc",
        "#e8dfee",
        "#d8e6da",
        "#99b89e",
        "#56875a",
        "#09581b",
    ),
    "teal_accent": (
        "#0a7b6e",
        "#767e85",
        "#868f96",
        "#97a0a7",
        "#a8b1b8",
        "#b9c3ca",
        "#cbd4dc",
        "#dde7ee",
    ),
    "coral_accent": (
        "#b54b43",
        "#767e85",
        "#868f96",
        "#97a0a7",
        "#a8b1b8",
        "#b9c3ca",
        "#cbd4dc",
        "#dde7ee",
    ),
    "accessible": (
        "#000000",
        "#e69f00",
        "#56b4e9",
        "#009e73",
        "#f0e442",
        "#0072b2",
        "#d55e00",
        "#cc79a7",
    ),
}

# name -> curation rationale + accessibility design targets (verbatim).
CURATED_META: dict[str, dict[str, str]] = {
    "warm_gray": {
        "label": "Warm Gray",
        "family": "Neutral",
        "band": "neutral · warm taupe ramp",
        "intent": "A hue-free ordered ramp with a WARM taupe or greige cast — for cream paper, editorial warmth, or warm brand systems. Encodes magnitude or rank without implying any category, staying soft and print-friendly from light to dark.",
        "design": "8-step light→dark L* ramp ≈92→22 at a warm hue (h≈70), chroma ≈ 5. Pure lightness ⇒ perfect B&W + CVD.",
        "application": "Warm-toned heat tables, ordered bars / area, backgrounds on cream stock.",
        "bw": "min ΔL* 9.7",
        "cvd": "d8.9 / p9.0 / t8.9",
    },
    "cool_gray": {
        "label": "Cool Gray",
        "family": "Neutral",
        "band": "neutral · cool slate ramp",
        "intent": "A hue-free ordered ramp with a COOL slate or blue cast — for tech, clinical, or cool brand systems. Encodes magnitude or rank without implying any category, holding a crisp, neutral tone the whole way from light to dark.",
        "design": "8-step light→dark L* ramp ≈92→22 at a cool hue (h≈250), chroma ≈ 6. Perfect B&W + CVD.",
        "application": "Cool-toned heat tables, ordered encodings, UI backgrounds.",
        "bw": "min ΔL* 9.7",
        "cvd": "d9.0 / p8.9 / t9.0",
    },
    "forest": {
        "label": "Forest",
        "family": "Analogous",
        "band": "narrow · green arc",
        "intent": "A few related series in a natural, organic register — ESG, agriculture, environment, growth themes. A green arc held to one hue family and separated by lightness, so the lines read as cohesive and calm rather than scattered or noisy.",
        "design": "A ~40° green arc (yellow-green→teal-green) on a staggered even L* ladder 36→90 — one hue family, lightness-separated.",
        "application": "Multi-series line / area for environmental or organic topics. Calm, cohesive.",
        "bw": "min ΔL* 7.7",
        "cvd": "d7.8 / p6.8 / t8.7",
    },
    "teal_indigo": {
        "label": "Teal → Indigo",
        "family": "Analogous",
        "band": "narrow · cool arc",
        "intent": "A few related series that should feel like ONE cool mood rather than a rainbow — cohesion over maximum distinctness. A teal-to-indigo arc separated by lightness, best for thin multi-line ensembles with an editorial, institutional tone.",
        "design": "A ~120° cool arc (teal→blue→indigo) on a staggered even L* ladder 38→90, so adjacent series contrast by lightness while sharing a family. Anchored on house teal.",
        "application": "Multi-series LINE ensembles (3-6 thin lines), area fills, refined scatter. Editorial / institutional tone.",
        "bw": "min ΔL* 7.4",
        "cvd": "d6.3 / p5.5 / t9.6",
    },
    "blue_orange": {
        "label": "Blue / Orange",
        "family": "Duo",
        "band": "medium · 180° split",
        "intent": "Two opposed groups using the single most colorblind-robust opposition, blue versus orange — A/B, gain/loss, before/after. The widest temperature split available, so the two sides stay clearly distinct even in grayscale or for CVD viewers.",
        "design": "4 blue + 4 orange hues (~180° apart), each an internal L* ramp; even ladder 38→90.",
        "application": "Grouped bars, two-cluster scatter, paired lines. Best-in-class CVD across all three types.",
        "bw": "min ΔL* 7.3",
        "cvd": "d12.6 / p12.2 / t14.8",
    },
    "teal_coral": {
        "label": "Teal / Coral",
        "family": "Duo",
        "band": "medium · 180° split",
        "intent": "Two opposed groups in the house-teal brand voice — teal against warm coral for A/B, before/after, or sentiment splits. The on-brand alternative to blue/orange, pairing the same temperature contrast with the dartwork identity color.",
        "design": "4 teal + 4 coral hues; even ladder 38→90. The warm side is pushed toward ORANGE (h≈44-68, not pure red) so the teal↔warm split lands on the blue-yellow axis and survives protanopia.",
        "application": "Brand-forward duos, grouped bars, paired lines. CVD-safe after the orange re-tune (still the softest of the three duos; for maximum accessibility, Blue/Orange or Warm/Cool lead).",
        "bw": "min ΔL* 7.2",
        "cvd": "d13.3 / p8.4 / t14.6",
    },
    "trustworthy": {
        "label": "Trustworthy",
        "family": "Balanced",
        "band": "medium-wide · teal + neutrals",
        "intent": "The everyday DEFAULT — reach for this first for 4 to 8 unrelated categories. Six evenly-spaced hues anchored on house teal plus two neutrals, muted enough to stay report-grade yet distinct enough that the series never tangle or shout.",
        "design": "6 evenly-spaced hues anchored on house teal + 2 neutrals, muted chroma (no neon), staggered even L* ladder 38→88.",
        "application": "Everything — line, bar, scatter; works on white pages and in tables. The general-purpose cycle.",
        "bw": "min ΔL* 7.1",
        "cvd": "d11.7 / p9.9 / t6.8",
    },
    "pastel": {
        "label": "Pastel",
        "family": "Muted",
        "band": "medium-wide · low chroma",
        "intent": "A soft, editorial categorical set for dense dashboards or backgrounds where vivid color would shout. High-key pastels carry 4 to 8 categories quietly, keeping the data readable without competing for attention on an already busy page.",
        "design": "Same 8-hue spread as the default but low chroma (~18) and a higher L* band 52→90. Calm, magazine-like. (B&W is softer by design.)",
        "application": "Dashboards, small multiples, annotation-heavy figures. Pair with one vivid accent for emphasis.",
        "bw": "min ΔL* 5.4",
        "cvd": "d5.9 / p4.8 / t6.3",
    },
    "dusty": {
        "label": "Dusty",
        "family": "Muted",
        "band": "deep · vintage muted",
        "intent": "A deeper, more vintage muted set — lower lightness than the high-key Pastel. Built for moody editorial, dark-on-cream layouts, and retro themes where soft-but-saturated tones suit the page better than bright, high-key color.",
        "design": "Same 8-hue spread as Muted but a mid L* band 40→78 and low chroma ~16. Calm but with more body than pastel.",
        "application": "Dense editorial, atmospheric dashboards, retro / vintage themes. (B&W softer by design.)",
        "bw": "min ΔL* 5.5",
        "cvd": "d6.2 / p5.1 / t6.5",
    },
    "vivid": {
        "label": "Vivid",
        "family": "Spectrum",
        "band": "widest · full wheel",
        "intent": "MANY unrelated categories — up to eight — where color alone must separate everything and maximum distinctness matters more than restraint. An even, vivid rainbow spread for legends, maps, and crowded categorical charts that need every series apart.",
        "design": "8 hues evenly spaced 45° around the full wheel (teal-anchored), high chroma, staggered even L* ladder 40→88 so it still survives B&W.",
        "application": "8-category scatter, side-by-side bars, editorial infographics. Vivid, confident tone.",
        "bw": "min ΔL* 6.1",
        "cvd": "d4.9 / p9.5 / t10.9",
    },
    "neon": {
        "label": "Neon",
        "family": "Spectrum",
        "band": "max chroma · electric",
        "intent": "MAXIMUM chroma — the loudest legal categorical, at the sRGB gamut edge. Up to 6 vivid categories on dark UI or hero moments.",
        "design": "Electric hues at the per-rung gamut ceiling; CVD-confusable pairs thrown far apart in L* so loudness never costs separability.",
        "application": "Dark-mode dashboards, brand hero charts, few-category small multiples.",
        "bw": "min ΔL* 7.0",
        "cvd": "d8.3 / p10.4 / t8.9",
    },
    "ember": {
        "label": "Ember",
        "family": "Tone",
        "band": "warm · vibrant",
        "intent": "The saturated WARM categorical — brick, coral, orange, amber, gold, olive plus a cool-neutral anchor. Golden-hour energy without earth's muteness.",
        "design": "All-warm hues carry little CVD margin, so the even L* stagger + a cool anchor + one green do the separating.",
        "application": "Warmth-themed dashboards, seasonal / energy / hospitality decks.",
        "bw": "min ΔL* 7.6",
        "cvd": "d5.3 / p4.9 / t8.1",
    },
    "earth": {
        "label": "Earth",
        "family": "Tone",
        "band": "warm · earthy",
        "intent": "Categorical series in a warm, organic register — ESG and sustainability, geography, agriculture, or premium-natural brands. Earthy, grounded hues that feel editorial and separate a handful of categories without ever looking corporate.",
        "design": "Terracotta, ochre, olive, sand, sage, clay (h 35→125, muted chroma ~26-30), staggered even L* ladder 36→88.",
        "application": "Multi-series line/bar/area for environmental or earthy topics. Calm, grounded, magazine-like.",
        "bw": "min ΔL* 7.2",
        "cvd": "d6.1 / p6.3 / t7.5",
    },
    "jewel": {
        "label": "Jewel",
        "family": "Tone",
        "band": "deep · rich saturation",
        "intent": "Rich, deep, saturated variety for premium or luxury editorial. Distinct from Vivid by going darker and deeper rather than brighter, so many categories stay separable while the whole set keeps an upscale, high-contrast mood.",
        "design": "Emerald, sapphire, indigo, vermilion, topaz, amethyst, deep teal/cyan (high chroma 42), even L* ladder 30→86. Retuned to clear the protanopia collapse.",
        "application": "Up to 8 categories where you want depth + luxury. ⚠ Softest CVD of the set (protan ~4) — for strict accessibility use Accessible or a Duo.",
        "bw": "min ΔL* 7.8",
        "cvd": "d7.6 / p4.2 / t16.3",
    },
    "cool_warm": {
        "label": "Cool ↔ Warm",
        "family": "Diverging",
        "band": "two-ended · pale center",
        "intent": "Ordered data with a meaningful MIDPOINT at zero — change, delta, correlation, z-scores, above or below average. Blue marks negative and red positive through a pale center, so both direction and magnitude read at a single glance.",
        "design": "Symmetric L* tent (dark ends → pale center), blue (h≈250) ↔ red (h≈25). Excellent CVD. NOT a categorical set — the order IS the meaning.",
        "application": "Correlation matrices, change heatmaps, anomaly/sentiment scales, Likert. ⚠ B&W not separable (ends share lightness — inherent to diverging).",
        "bw": "min ΔL* 0.0",
        "cvd": "d12.6 / p13.6 / t14.2",
    },
    "teal_amber": {
        "label": "Teal ↔ Amber",
        "family": "Diverging",
        "band": "two-ended · pale center",
        "intent": "The diverging intent in the house voice — teal for negative and amber for positive through a pale neutral center. An on-brand alternative to blue-red for deltas, correlations, and above-or-below-average encodings on branded material.",
        "design": "Symmetric L* tent, teal (h≈186) ↔ amber (h≈66). The blue-yellow axis is CVD-robust.",
        "application": "Brand-forward change/delta heatmaps, ± scales. ⚠ B&W not separable by design.",
        "bw": "min ΔL* 0.0",
        "cvd": "d13.1 / p8.8 / t13.9",
    },
    "purple_green": {
        "label": "Purple / Green",
        "family": "Diverging",
        "band": "two-ended · pale center",
        "intent": "Diverging purple to green around a pale centre (PRGn lineage) — the TRITAN-robust axis that blue-orange and teal-amber lack.",
        "design": "Symmetric even-L* tent: dark saturated ends, pale low-chroma centre; both arms separable under all three CVD types.",
        "application": "Signed quantities where blue-yellow deficiency must be covered.",
        "bw": "min ΔL* 0.0",
        "cvd": "d8.6 / p10.4 / t8.1",
    },
    "teal_accent": {
        "label": "Teal Accent",
        "family": "Emphasis",
        "band": "1 teal accent + 7 neutrals",
        "intent": "Highlight ONE series while everything else recedes to gray — the storytelling staple, color the one thing. House teal marks the salient series and graded neutrals carry the rest, keeping attention exactly where you point it.",
        "design": "Slot 0 = house teal (salient), slots 1-7 = graded neutrals on an even L* ladder 46→91. Pair with Coral Accent for the warm-highlight version, or combine the two accent colors to highlight a second series.",
        "application": "Single-series emphasis in line / bar charts, explanatory figures, slide builds.",
        "bw": "min ΔL* 6.2",
        "cvd": "d5.8 / p5.7 / t5.8",
    },
    "coral_accent": {
        "label": "Coral Accent",
        "family": "Emphasis",
        "band": "1 warm accent + 7 neutrals",
        "intent": "Highlight one series with a WARM coral accent instead of teal — for warmth, alerts, or when teal clashes with the content. Coral marks the salient line and graded neutrals mute everything else quietly into the background.",
        "design": "Slot 0 = coral (h≈32, salient), slots 1-7 = graded neutrals, even L* ladder 46→91.",
        "application": "Single-series emphasis where a warm highlight reads better (e.g., risk / attention).",
        "bw": "min ΔL* 6.2",
        "cvd": "d5.8 / p5.7 / t5.8",
    },
    "accessible": {
        "label": "Okabe-Ito",
        "family": "Accessible",
        "band": "widest · CVD gold standard",
        "intent": "When colorblind-safety is mandatory — journals, public-sector, clinical work. The proven Okabe-Ito CUD eight-color set shipped verbatim, so every pair stays distinguishable under all of the common forms of color-vision deficiency.",
        "design": "Fixed Okabe & Ito (2008) palette — NOT regenerated. Tuned for deuter/protan/tritan separation (the strongest in the family).",
        "application": "Any figure where CVD accessibility is a hard requirement. Not built for B&W (near-equal lightness) — don't lean on grayscale for this one.",
        "bw": "min ΔL* 0.8",
        "cvd": "d14.8 / p14.0 / t11.0",
    },
}

__all__ = ["CURATED", "CURATED_META", "CURATED_ORDER"]
